### ISSUE TITLE
Release tag != Release tag

### ISSUE THREAD

**Issue by januridp** [coronatorid/landingpage#2]
`export RELEASE_TAG=$(echo $GITHUB_SHA | awk '{print substr($0,0,7)}')`
apa memang maunya seperti itu? jika iya berarti salah nama? atau memang mau tag tapi gimana?
$GITHUB_SHA itu commit-nya kan? rilis tag itu yang release-20201227-213400 kan?

**Comment by insomnius** [comment]
Salah terminologi, boleh aja diganti jadi `TAG`. Karena sebenernya itu untuk docker tag yang nanti akan di pull oleh server. Tapi kalau diganti, maka di contooling juga harus diganti.
